In [ ]:
import pandas as pd

In [ ]:
pip install yfinance pandas

Requirement already satisfied: yfinance in /usr/local/lib/python3.13/dist-packages (0.2.66)
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.16.5 in /usr/local/lib/python3.13/dist-packages (from yfinance) (2.1.3)
Requirement already satisfied: requests>=2.31 in /usr/local/lib/python3.13/dist-packages (from yfinance) (2.32.4)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.13/dist-packages (from yfinance) (0.0.13)
Requirement already satisfied: platformdirs>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from yfinance) (4.12.2)
Requirement already satisfied: pytz>=2022.5 in /usr/local/lib/python3.13/dist-packages (from yfinance) (2025.2)
Requirement already satisfied: frozendict>=2.3.4 in /usr/local/lib/python3.13/dist-packages (from yfinance) (2.4.7)
Requirement already satisfied: peewee>=3.16.2 in /usr/local/lib/python3.13/dist-packages (from yfinance) (4.5.2)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /usr/local/lib/python3.13/dist-packages (from yfinance) (4.13.5)
Requirement already satisfied: curl_cffi>=0.7 in /usr/local/lib/python3.13/dist-packages (from yfinance) (0.16.3)
Requirement already satisfied: protobuf>=3.19.0 in /usr/local/lib/python3.13/dist-packages (from yfinance) (6.33.6)
Requirement already satisfied: websockets>=13.0 in /usr/local/lib/python3.13/dist-packages (from yfinance) (15.0.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.4)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.13/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (2.10)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.13/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (4.16.0)
Requirement already satisfied: cffi>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from curl_cffi>=0.7->yfinance) (2.1.1)
Requirement already satisfied: certifi>=2024.2.2 in /usr/local/lib/python3.13/dist-packages (from curl_cffi>=0.7->yfinance) (2026.7.22)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests>=2.31->yfinance) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests>=2.31->yfinance) (3.20)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests>=2.31->yfinance) (2.5.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.13/dist-packages (from cffi>=2.0.0->curl_cffi>=0.7->yfinance) (3.0)

In [ ]:
import yfinance as yf

In [ ]:
acao = yf.Ticker('ITUB4.SA')
data = acao.history(period='1y')

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
df

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2025-10-07 00:00:00-03:00,33.874719,33.883696,33.201175,33.380787,20705472,0.000000,0.0
2025-10-08 00:00:00-03:00,33.452618,33.632230,33.273009,33.443638,15395204,0.000000,0.0
2025-10-09 00:00:00-03:00,33.605296,33.605296,33.192190,33.389763,18067539,0.000000,0.0
2025-10-10 00:00:00-03:00,33.560397,33.731029,33.255057,33.353844,23250808,0.000000,0.0
2025-10-13 00:00:00-03:00,33.479564,33.704078,33.479564,33.488544,8194989,0.000000,0.0
...,...,...,...,...,...,...,...
2026-10-01 00:00:00-03:00,44.349998,44.630001,43.410000,44.139999,58873000,0.018182,0.0
2026-10-02 00:00:00-03:00,45.250000,45.270000,43.099998,44.830002,44876100,0.000000,0.0
2026-10-05 00:00:00-03:00,48.799999,50.680000,48.080002,49.480000,105387700,0.000000,0.0
2026-10-06 00:00:00-03:00,49.950001,50.849998,49.730000,50.450001,58027100,0.000000,0.0
2026-10-07 00:00:00-03:00,50.299999,50.790001,48.919998,49.110001,46412300,0.000000,0.0

In [ ]:
df = data.filter(items=['Open', 'Close'])
df

                                Open      Close
Date
2025-10-07 00:00:00-03:00  33.874719  33.380787
2025-10-08 00:00:00-03:00  33.452633  33.443653
2025-10-09 00:00:00-03:00  33.605296  33.389763
2025-10-10 00:00:00-03:00  33.560385  33.353832
2025-10-13 00:00:00-03:00  33.479568  33.488548
...                              ...        ...
2026-10-01 00:00:00-03:00  44.349998  44.139999
2026-10-02 00:00:00-03:00  45.250000  44.830002
2026-10-05 00:00:00-03:00  48.799999  49.480000
2026-10-06 00:00:00-03:00  49.950001  50.450001
2026-10-07 00:00:00-03:00  50.299999  49.110001

[250 rows x 2 columns]

In [ ]:
df = data.filter(like='Dividends', axis=1)
df

                           Dividends
Date
2025-10-07 00:00:00-03:00   0.000000
2025-10-08 00:00:00-03:00   0.000000
2025-10-09 00:00:00-03:00   0.000000
2025-10-10 00:00:00-03:00   0.000000
2025-10-13 00:00:00-03:00   0.000000
...                              ...
2026-10-01 00:00:00-03:00   0.018182
2026-10-02 00:00:00-03:00   0.000000
2026-10-05 00:00:00-03:00   0.000000
2026-10-06 00:00:00-03:00   0.000000
2026-10-07 00:00:00-03:00   0.000000

[250 rows x 1 columns]

In [ ]:
df = data[(data.index > '2026-10-05')]
df

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2026-10-06 00:00:00-03:00,49.950001,50.849998,49.730000,50.450001,58027100,0.0,0.0
2026-10-07 00:00:00-03:00,50.299999,50.790001,48.919998,49.110001,46412300,0.0,0.0

In [ ]:
df = data[['Open', 'Close', 'High']]
df

                                Open      Close       High
Date
2025-10-07 00:00:00-03:00  33.874719  33.380787  33.883696
2025-10-08 00:00:00-03:00  33.452633  33.443653  33.632246
2025-10-09 00:00:00-03:00  33.605296  33.389763  33.605296
2025-10-10 00:00:00-03:00  33.560385  33.353832  33.731017
2025-10-13 00:00:00-03:00  33.479568  33.488548  33.704082
...                              ...        ...        ...
2026-10-01 00:00:00-03:00  44.349998  44.139999  44.630001
2026-10-02 00:00:00-03:00  45.250000  44.830002  45.270000
2026-10-05 00:00:00-03:00  48.799999  49.480000  50.680000
2026-10-06 00:00:00-03:00  49.950001  50.450001  50.849998
2026-10-07 00:00:00-03:00  50.299999  49.110001  50.790001

[250 rows x 3 columns]

In [ ]:
df = data.index
df

DatetimeIndex(['2025-10-07 00:00:00-03:00', '2025-10-08 00:00:00-03:00',
               '2025-10-09 00:00:00-03:00', '2025-10-10 00:00:00-03:00',
               '2025-10-13 00:00:00-03:00', '2025-10-14 00:00:00-03:00',
               '2025-10-15 00:00:00-03:00', '2025-10-16 00:00:00-03:00',
               '2025-10-17 00:00:00-03:00', '2025-10-20 00:00:00-03:00',
               ...
               '2026-09-24 00:00:00-03:00', '2026-09-25 00:00:00-03:00',
               '2026-09-28 00:00:00-03:00', '2026-09-29 00:00:00-03:00',
               '2026-09-30 00:00:00-03:00', '2026-10-01 00:00:00-03:00',
               '2026-10-02 00:00:00-03:00', '2026-10-05 00:00:00-03:00',
               '2026-10-06 00:00:00-03:00', '2026-10-07 00:00:00-03:00'],
              dtype='datetime64[ns, America/Sao_Paulo]', name='Date', length=250, freq=None)