In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_excel('/content/planilha_vendas.xlsx')
df

,produto,garantia extendida,pais,quantidade,valorunitario
0,Google Pixel 8,Não,Estados Unidos,4,8480.90
1,iPhone 14,Não,Japão,3,7947.22
2,Motorola Edge 40,Não,França,1,2464.76
3,Motorola Edge 40,Sim,Reino Unido,1,2768.03
4,iPhone 15 Pro,Sim,Brasil,5,6040.08
...,...,...,...,...,...
95,Xiaomi Mi 13,Não,Coreia do Sul,1,2923.03
96,Xiaomi Mi 13,Não,França,2,2784.93
97,iPhone 14,Sim,Alemanha,5,7304.95
98,Samsung A54,Não,Alemanha,2,2916.62
99,Motorola Edge 40,Não,França,2,1347.22

In [ ]:
pd.crosstab(df.pais, df.produto)

produto,Google Pixel 8,Motorola Edge 40,Motorola Moto G54,OnePlus 11,Samsung A54,Samsung S24 Ultra,Xiaomi Mi 13,Xiaomi Redmi Note 12,iPhone 14,iPhone 15 Pro
pais,,,,,,,,,,
Alemanha,1,2,1,1,2,1,1,0,3,0
Brasil,2,1,0,1,0,1,2,0,4,2
Canadá,3,2,1,2,1,1,0,1,0,2
Coreia do Sul,0,2,1,1,2,0,3,3,0,0
Estados Unidos,1,2,0,0,2,0,1,5,2,1
França,1,2,0,1,0,0,2,2,3,3
Japão,0,0,3,0,1,0,0,0,3,2
Reino Unido,2,1,2,0,3,1,3,0,0,1

In [ ]:
pd.crosstab(df.pais, df.produto, margins=True)

produto,Google Pixel 8,Motorola Edge 40,Motorola Moto G54,OnePlus 11,Samsung A54,Samsung S24 Ultra,Xiaomi Mi 13,Xiaomi Redmi Note 12,iPhone 14,iPhone 15 Pro,All
pais,,,,,,,,,,,
Alemanha,1,2,1,1,2,1,1,0,3,0,12
Brasil,2,1,0,1,0,1,2,0,4,2,13
Canadá,3,2,1,2,1,1,0,1,0,2,13
Coreia do Sul,0,2,1,1,2,0,3,3,0,0,12
Estados Unidos,1,2,0,0,2,0,1,5,2,1,14
França,1,2,0,1,0,0,2,2,3,3,14
Japão,0,0,3,0,1,0,0,0,3,2,9
Reino Unido,2,1,2,0,3,1,3,0,0,1,13
All,10,12,8,6,11,4,12,11,15,11,100

In [ ]:
pd.crosstab(df.pais, [df.produto, df['garantia extendida']], margins=True)

produto            Google Pixel 8     Motorola Edge 40     Motorola Moto G54  \
garantia extendida            Não Sim              Não Sim               Não
pais
Alemanha                        0   1                0   2                 0
Brasil                          1   1                0   1                 0
Canadá                          1   2                0   2                 0
Coreia do Sul                   0   0                0   2                 1
Estados Unidos                  1   0                2   0                 0
França                          1   0                2   0                 0
Japão                           0   0                0   0                 1
Reino Unido                     0   2                0   1                 1
All                             4   6                4   8                 3

produto                OnePlus 11     Samsung A54      ... Samsung S24 Ultra  \
garantia extendida Sim        Não Sim         Não Sim  ...               Sim
pais                                                   ...
Alemanha             1          0   1           2   0  ...                 1
Brasil               0          0   1           0   0  ...                 1
Canadá               1          0   2           1   0  ...                 0
Coreia do Sul        0          1   0           0   2  ...                 0
Estados Unidos       0          0   0           1   1  ...                 0
França               0          0   1           0   0  ...                 0
Japão                2          0   0           0   1  ...                 0
Reino Unido          1          0   0           2   1  ...                 0
All                  5          1   5           6   5  ...                 2

produto            Xiaomi Mi 13     Xiaomi Redmi Note 12     iPhone 14      \
garantia extendida          Não Sim                  Não Sim       Não Sim
pais
Alemanha                      0   1                    0   0         1   2
Brasil                        0   2                    0   0         0   4
Canadá                        0   0                    1   0         0   0
Coreia do Sul                 1   2                    0   3         0   0
Estados Unidos                0   1                    1   4         1   1
França                        2   0                    2   0         1   2
Japão                         0   0                    0   0         2   1
Reino Unido                   1   2                    0   0         0   0
All                           4   8                    4   7         5  10

produto            iPhone 15 Pro      All
garantia extendida           Não Sim
pais
Alemanha                       0   0   12
Brasil                         1   1   13
Canadá                         1   1   13
Coreia do Sul                  0   0   12
Estados Unidos                 0   1   14
França                         2   1   14
Japão                          0   2    9
Reino Unido                    1   0   13
All                            5   6  100

[9 rows x 21 columns]

In [ ]:
pd.crosstab([df.produto], [df.pais], values=df.quantidade, aggfunc=np.sum, margins=True)

/tmp/ipykernel_566/1998845907.py:1: FutureWarning: The provided callable <function sum at 0x78b765170ea0> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  pd.crosstab([df.produto], [df.pais], values=df.quantidade, aggfunc=np.sum, margins=True)
/tmp/ipykernel_566/1998845907.py:1: FutureWarning: The provided callable <function sum at 0x78b765170ea0> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  pd.crosstab([df.produto], [df.pais], values=df.quantidade, aggfunc=np.sum, margins=True)
/tmp/ipykernel_566/1998845907.py:1: FutureWarning: The provided callable <function sum at 0x78b765170ea0> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  pd.crosstab([df.produto], [df.pais], values=df.quantidade, aggfunc=np.sum, margins=True)

pais,Alemanha,Brasil,Canadá,Coreia do Sul,Estados Unidos,França,Japão,Reino Unido,All
produto,,,,,,,,,
Google Pixel 8,5.0,6.0,13.0,NaN,4.0,5.0,NaN,7.0,40
Motorola Edge 40,7.0,4.0,9.0,5.0,7.0,3.0,NaN,1.0,36
Motorola Moto G54,3.0,NaN,3.0,4.0,NaN,NaN,10.0,8.0,28
OnePlus 11,5.0,4.0,4.0,1.0,NaN,4.0,NaN,NaN,18
Samsung A54,7.0,NaN,4.0,6.0,6.0,NaN,3.0,9.0,35
Samsung S24 Ultra,5.0,3.0,5.0,NaN,NaN,NaN,NaN,3.0,16
Xiaomi Mi 13,5.0,6.0,NaN,5.0,2.0,7.0,NaN,10.0,35
Xiaomi Redmi Note 12,NaN,NaN,3.0,7.0,14.0,5.0,NaN,NaN,29
iPhone 14,8.0,16.0,NaN,NaN,7.0,12.0,8.0,NaN,51
iPhone 15 Pro,NaN,7.0,10.0,NaN,1.0,9.0,6.0,2.0,35
All,45.0,46.0,51.0,28.0,41.0,45.0,27.0,40.0,323

In [ ]:
pd.crosstab([df.produto], [df.pais], values=df.quantidade, aggfunc=np.sum, margins=True)

In [ ]:
df['valor_total'] = df.valorunitario * df.quantidade

df2 = df.copy()
df2

,produto,garantia extendida,pais,quantidade,valorunitario,valor_total
0,Google Pixel 8,Não,Estados Unidos,4,8480.90,33923.60
1,iPhone 14,Não,Japão,3,7947.22,23841.66
2,Motorola Edge 40,Não,França,1,2464.76,2464.76
3,Motorola Edge 40,Sim,Reino Unido,1,2768.03,2768.03
4,iPhone 15 Pro,Sim,Brasil,5,6040.08,30200.40
...,...,...,...,...,...,...
95,Xiaomi Mi 13,Não,Coreia do Sul,1,2923.03,2923.03
96,Xiaomi Mi 13,Não,França,2,2784.93,5569.86
97,iPhone 14,Sim,Alemanha,5,7304.95,36524.75
98,Samsung A54,Não,Alemanha,2,2916.62,5833.24
99,Motorola Edge 40,Não,França,2,1347.22,2694.44

In [ ]:
pd.crosstab(df2.pais, df2.produto, normalize='index')

produto,Google Pixel 8,Motorola Edge 40,Motorola Moto G54,OnePlus 11,Samsung A54,Samsung S24 Ultra,Xiaomi Mi 13,Xiaomi Redmi Note 12,iPhone 14,iPhone 15 Pro
pais,,,,,,,,,,
Alemanha,0.083333,0.166667,0.083333,0.083333,0.166667,0.083333,0.083333,0.000000,0.250000,0.000000
Brasil,0.153846,0.076923,0.000000,0.076923,0.000000,0.076923,0.153846,0.000000,0.307692,0.153846
Canadá,0.230769,0.153846,0.076923,0.153846,0.076923,0.076923,0.000000,0.076923,0.000000,0.153846
Coreia do Sul,0.000000,0.166667,0.083333,0.083333,0.166667,0.000000,0.250000,0.250000,0.000000,0.000000
Estados Unidos,0.071429,0.142857,0.000000,0.000000,0.142857,0.000000,0.071429,0.357143,0.142857,0.071429
França,0.071429,0.142857,0.000000,0.071429,0.000000,0.000000,0.142857,0.142857,0.214286,0.214286
Japão,0.000000,0.000000,0.333333,0.000000,0.111111,0.000000,0.000000,0.000000,0.333333,0.222222
Reino Unido,0.153846,0.076923,0.153846,0.000000,0.230769,0.076923,0.230769,0.000000,0.000000,0.076923

In [ ]:
pd.crosstab(df2.pais, df2.produto, normalize='index').round(4)*100

produto,Google Pixel 8,Motorola Edge 40,Motorola Moto G54,OnePlus 11,Samsung A54,Samsung S24 Ultra,Xiaomi Mi 13,Xiaomi Redmi Note 12,iPhone 14,iPhone 15 Pro
pais,,,,,,,,,,
Alemanha,8.33,16.67,8.33,8.33,16.67,8.33,8.33,0.00,25.00,0.00
Brasil,15.38,7.69,0.00,7.69,0.00,7.69,15.38,0.00,30.77,15.38
Canadá,23.08,15.38,7.69,15.38,7.69,7.69,0.00,7.69,0.00,15.38
Coreia do Sul,0.00,16.67,8.33,8.33,16.67,0.00,25.00,25.00,0.00,0.00
Estados Unidos,7.14,14.29,0.00,0.00,14.29,0.00,7.14,35.71,14.29,7.14
França,7.14,14.29,0.00,7.14,0.00,0.00,14.29,14.29,21.43,21.43
Japão,0.00,0.00,33.33,0.00,11.11,0.00,0.00,0.00,33.33,22.22
Reino Unido,15.38,7.69,15.38,0.00,23.08,7.69,23.08,0.00,0.00,7.69

In [54]:
df_tipo_cell = df.groupby('produto')
df_tipo_cell

In [55]:
df_tipo_cell.ngroups

10

In [56]:
df.groupby('pais').ngroups

8

In [57]:
df.groupby('pais').groups

{'Alemanha': [18, 21, 30, 36, 47, 55, 57, 60, 68, 91, 97, 98], 'Brasil': [4, 5, 9, 17, 24, 27, 37, 48, 51, 61, 63, 82, 83], 'Canadá': [8, 22, 23, 33, 35, 40, 49, 56, 67, 70, 79, 87, 90], 'Coreia do Sul': [11, 26, 34, 39, 43, 44, 52, 53, 64, 72, 84, 95], 'Estados Unidos': [0, 6, 7, 13, 14, 19, 25, 41, 62, 65, 71, 74, 77, 78], 'França': [2, 10, 16, 28, 31, 45, 54, 59, 73, 80, 88, 89, 96, 99], 'Japão': [1, 12, 15, 20, 58, 69, 75, 81, 94], 'Reino Unido': [3, 29, 32, 38, 42, 46, 50, 66, 76, 85, 86, 92, 93]}

In [59]:
df.groupby('pais').size()

pais
Alemanha          12
Brasil            13
Canadá            13
Coreia do Sul     12
Estados Unidos    14
França            14
Japão              9
Reino Unido       13
dtype: int64

In [65]:
df.groupby('pais').get_group('Brasil')

,produto,garantia extendida,pais,quantidade,valorunitario,valor_total
4,iPhone 15 Pro,Sim,Brasil,5,6040.08,30200.40
5,Google Pixel 8,Não,Brasil,4,8749.77,34999.08
9,iPhone 14,Sim,Brasil,4,6665.53,26662.12
17,iPhone 15 Pro,Não,Brasil,2,4836.31,9672.62
24,iPhone 14,Sim,Brasil,5,8587.06,42935.30
27,Xiaomi Mi 13,Sim,Brasil,5,2880.97,14404.85
37,OnePlus 11,Sim,Brasil,4,1659.03,6636.12
48,Motorola Edge 40,Sim,Brasil,4,1228.09,4912.36
51,Google Pixel 8,Sim,Brasil,2,8436.96,16873.92
61,iPhone 14,Sim,Brasil,5,5053.40,25267.00
63,Xiaomi Mi 13,Sim,Brasil,1,1331.39,1331.39
82,Samsung S24 Ultra,Sim,Brasil,3,6950.64,20851.92
83,iPhone 14,Sim,Brasil,2,5287.84,10575.68

In [73]:
df.groupby('pais').mean(numeric_only=True)

                quantidade  valorunitario   valor_total
pais
Alemanha          3.750000    4354.917500  15781.694167
Brasil            3.538462    5208.236154  18870.981538
Canadá            3.923077    3864.995385  16468.130000
Coreia do Sul     2.333333    1828.142500   4038.357500
Estados Unidos    2.928571    3386.765000  10042.249286
França            3.214286    4253.716429  14591.409286
Japão             3.000000    4760.742222  13361.537778
Reino Unido       3.076923    3501.050000  10202.455385

In [77]:
df.groupby(['pais', 'produto',])['valor_total'].sum()

pais            produto
Alemanha        Google Pixel 8           44645.70
                Motorola Edge 40         16164.64
                Motorola Moto G54         2845.47
                OnePlus 11                9202.40
                Samsung A54              19351.34
                Samsung S24 Ultra        23038.65
                Xiaomi Mi 13             14691.15
                iPhone 14                59440.98
Brasil          Google Pixel 8           51873.00
                Motorola Edge 40          4912.36
                OnePlus 11                6636.12
                Samsung S24 Ultra        20851.92
                Xiaomi Mi 13             15736.24
                iPhone 14               105440.10
                iPhone 15 Pro            39873.02
Canadá          Google Pixel 8           62456.46
                Motorola Edge 40         21067.09
                Motorola Moto G54         5177.07
                OnePlus 11                5814.47
                Samsung A54               5498.80
                Samsung S24 Ultra        36872.25
                Xiaomi Redmi Note 12      8789.40
                iPhone 15 Pro            68410.15
Coreia do Sul   Motorola Edge 40          9345.33
                Motorola Moto G54         7456.08
                OnePlus 11                1476.32
                Samsung A54               9255.78
                Xiaomi Mi 13              8229.98
                Xiaomi Redmi Note 12     12696.80
Estados Unidos  Google Pixel 8           33923.60
                Motorola Edge 40         11983.30
                Samsung A54               7114.44
                Xiaomi Mi 13              2210.70
                Xiaomi Redmi Note 12     28080.03
                iPhone 14                50805.49
                iPhone 15 Pro             6473.93
França          Google Pixel 8           31433.40
                Motorola Edge 40          5159.20
                OnePlus 11                4465.76
                Xiaomi Mi 13             17400.21
                Xiaomi Redmi Note 12     11459.13
                iPhone 14                70926.87
                iPhone 15 Pro            63435.16
Japão           Motorola Moto G54        16574.59
                Samsung A54               6261.54
                iPhone 14                55055.01
                iPhone 15 Pro            42362.70
Reino Unido     Google Pixel 8           42424.31
                Motorola Edge 40          2768.03
                Motorola Moto G54        21597.52
                Samsung A54              16392.63
                Samsung S24 Ultra        19706.55
                Xiaomi Mi 13             15442.18
                iPhone 15 Pro            14300.70
Name: valor_total, dtype: float64