In [2]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv('/content/bovespa_tidy.csv')
df

     Ticker        Date      Close       High        Low       Open    Volume
0     VALE3  2024-10-09  51.927876  52.013061  51.323073  51.680843  22758400
1     VALE3  2024-10-10  52.174911  52.345279  51.748994  52.345279  17192100
2     VALE3  2024-10-11  52.924522  53.043779  51.944911  51.953431  20939400
3     VALE3  2024-10-14  52.754158  53.256741  52.243058  53.086373  44954000
4     VALE3  2024-10-15  52.106762  52.132319  51.595662  52.047134  25559300
...     ...         ...        ...        ...        ...        ...       ...
3987  MGLU3  2026-10-05   9.450000   9.790000   8.430000   8.430000  65568900
3988  MGLU3  2026-10-06   9.240000   9.920000   9.200000   9.510000  47644200
3989  MGLU3  2026-10-07   9.710000  10.080000   9.200000   9.230000  51155600
3990  MGLU3  2026-10-08  10.250000  10.830000   9.600000   9.750000  56420800
3991  MGLU3  2026-10-09  12.220000  12.450000  10.360000  10.550000  77512100

[3992 rows x 7 columns]

In [5]:
df_itau = df[df['Ticker'] == 'ITUB4']
df_itau

     Ticker        Date      Close       High        Low       Open     Volume
998   ITUB4  2024-10-09  26.124155  26.500584  26.071457  26.432827   23707005
999   ITUB4  2024-10-10  26.267200  26.327428  26.026286  26.131686   23211884
1000  ITUB4  2024-10-11  26.071455  26.327425  26.011226  26.222025   19225310
1001  ITUB4  2024-10-14  26.237083  26.402711  26.063926  26.154269   16356101
1002  ITUB4  2024-10-15  26.538229  26.583401  26.146744  26.274729   32631872
...     ...         ...        ...        ...        ...        ...        ...
1492  ITUB4  2026-10-05  49.480000  50.680000  48.080002  48.799999  105387700
1493  ITUB4  2026-10-06  50.450001  50.849998  49.730000  49.950001   58027100
1494  ITUB4  2026-10-07  49.110001  50.790001  48.919998  50.299999   46569000
1495  ITUB4  2026-10-08  49.349998  49.849998  48.250000  49.000000   40125700
1496  ITUB4  2026-10-09  50.470001  50.779999  49.480000  49.759998   46965400

[499 rows x 7 columns]

In [6]:
df_itau.dtypes

Ticker     object
Date       object
Close     float64
High      float64
Low       float64
Open      float64
Volume      int64
dtype: object

In [12]:
df_itau['Date'] = pd.to_datetime(df_itau['Date'], format= '%y-%m-d')
df_itau.dtypes

/tmp/ipykernel_394/3911521119.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_itau['Date'] = pd.to_datetime(df_itau['Date'], format= '%y-%m-d')

Ticker            object
Date      datetime64[ns]
Close            float64
High             float64
Low              float64
Open             float64
Volume             int64
dtype: object

In [13]:
df_itau

     Ticker       Date      Close       High        Low       Open     Volume
998   ITUB4 2024-10-09  26.124155  26.500584  26.071457  26.432827   23707005
999   ITUB4 2024-10-10  26.267200  26.327428  26.026286  26.131686   23211884
1000  ITUB4 2024-10-11  26.071455  26.327425  26.011226  26.222025   19225310
1001  ITUB4 2024-10-14  26.237083  26.402711  26.063926  26.154269   16356101
1002  ITUB4 2024-10-15  26.538229  26.583401  26.146744  26.274729   32631872
...     ...        ...        ...        ...        ...        ...        ...
1492  ITUB4 2026-10-05  49.480000  50.680000  48.080002  48.799999  105387700
1493  ITUB4 2026-10-06  50.450001  50.849998  49.730000  49.950001   58027100
1494  ITUB4 2026-10-07  49.110001  50.790001  48.919998  50.299999   46569000
1495  ITUB4 2026-10-08  49.349998  49.849998  48.250000  49.000000   40125700
1496  ITUB4 2026-10-09  50.470001  50.779999  49.480000  49.759998   46965400

[499 rows x 7 columns]

In [26]:
df_itau['mm5d'] = df_itau['Close'].rolling(5).mean()
df_itau['mm21d'] = df_itau['Close'].rolling(21).mean()
df_itau['mm60d'] = df_itau['Close'].rolling(60).mean()
df_itau

/tmp/ipykernel_394/1580309111.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_itau['mm5d'] = df_itau['Close'].rolling(5).mean()
/tmp/ipykernel_394/1580309111.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_itau['mm21d'] = df_itau['Close'].rolling(21).mean()
/tmp/ipykernel_394/1580309111.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_itau['mm60d'] = df_itau['Close'].rolling(60).mean()

,Ticker,Date,Close,High,Low,Open,Volume,mm5d,mm21d,mm60d
998,ITUB4,2024-10-09,26.124155,26.500584,26.071457,26.432827,23707005,NaN,NaN,NaN
999,ITUB4,2024-10-10,26.267200,26.327428,26.026286,26.131686,23211884,NaN,NaN,NaN
1000,ITUB4,2024-10-11,26.071455,26.327425,26.011226,26.222025,19225310,NaN,NaN,NaN
1001,ITUB4,2024-10-14,26.237083,26.402711,26.063926,26.154269,16356101,NaN,NaN,NaN
1002,ITUB4,2024-10-15,26.538229,26.583401,26.146744,26.274729,32631872,26.247625,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
1492,ITUB4,2026-10-05,49.480000,50.680000,48.080002,48.799999,105387700,44.998890,42.982194,41.604881
1493,ITUB4,2026-10-06,50.450001,50.849998,49.730000,49.950001,58027100,46.632364,43.389205,41.721320
1494,ITUB4,2026-10-07,49.110001,50.790001,48.919998,50.299999,46569000,47.602000,43.708130,41.813594
1495,ITUB4,2026-10-08,49.349998,49.849998,48.250000,49.000000,40125700,48.644000,44.078467,41.918024
1496,ITUB4,2026-10-09,50.470001,50.779999,49.480000,49.759998,46965400,49.772000,44.465961,42.050942

In [29]:
features = df_itau.drop(['Ticker', 'Date', 'Close'], 1)
features

,High,Low,Open,Volume,mm5d,mm21d,mm60d
998,26.500584,26.071457,26.432827,23707005,NaN,NaN,NaN
999,26.327428,26.026286,26.131686,23211884,NaN,NaN,NaN
1000,26.327425,26.011226,26.222025,19225310,NaN,NaN,NaN
1001,26.402711,26.063926,26.154269,16356101,NaN,NaN,NaN
1002,26.583401,26.146744,26.274729,32631872,26.247625,NaN,NaN
...,...,...,...,...,...,...,...
1492,50.680000,48.080002,48.799999,105387700,44.998890,42.982194,41.604881
1493,50.849998,49.730000,49.950001,58027100,46.632364,43.389205,41.721320
1494,50.790001,48.919998,50.299999,46569000,47.602000,43.708130,41.813594
1495,49.849998,48.250000,49.000000,40125700,48.644000,44.078467,41.918024
1496,50.779999,49.480000,49.759998,46965400,49.772000,44.465961,42.050942

In [57]:
df = pd.read_csv('http://bit.ly/kaggletrain')
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [43]:
sex = pd.get_dummies(df.Sex)
sex

     female   male
0     False   True
1      True  False
2      True  False
3      True  False
4     False   True
..      ...    ...
886   False   True
887    True  False
888    True  False
889   False   True
890   False   True

[891 rows x 2 columns]

In [59]:
emb = pd.get_dummies(df.Embarked)
emb

         C      Q      S
0    False  False   True
1     True  False  False
2    False  False   True
3    False  False   True
4    False  False   True
..     ...    ...    ...
886  False  False   True
887  False  False   True
888  False  False   True
889   True  False  False
890  False   True  False

[891 rows x 3 columns]

In [58]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [60]:
df = pd.concat([df, emb], axis=1)
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,C,Q,S
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,False,False,True
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,True,False,False
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,False,False,True
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,False,False,True
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,False,False,True
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,False,False,True
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,False,False,True
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,True,False,False
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,False,True,False

In [61]:
df2 = pd.get_dummies(df, columns=['Sex'], drop_first=True)
df2

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,C,Q,S,Sex_male
0,1,0,3,"Braund, Mr. Owen Harris",22.0,1,0,A/5 21171,7.2500,NaN,S,False,False,True,True
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,1,0,PC 17599,71.2833,C85,C,True,False,False,False
2,3,1,3,"Heikkinen, Miss. Laina",26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,False,False,True,False
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,1,0,113803,53.1000,C123,S,False,False,True,False
4,5,0,3,"Allen, Mr. William Henry",35.0,0,0,373450,8.0500,NaN,S,False,False,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",27.0,0,0,211536,13.0000,NaN,S,False,False,True,True
887,888,1,1,"Graham, Miss. Margaret Edith",19.0,0,0,112053,30.0000,B42,S,False,False,True,False
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",NaN,1,2,W./C. 6607,23.4500,NaN,S,False,False,True,False
889,890,1,1,"Behr, Mr. Karl Howell",26.0,0,0,111369,30.0000,C148,C,True,False,False,True
890,891,0,3,"Dooley, Mr. Patrick",32.0,0,0,370376,7.7500,NaN,Q,False,True,False,True