In [11]:
import pandas as pd

In [1]:
frutas = ['maça', 'banana', 'abacaxi']
frutas

['maça', 'banana', 'abacaxi']

In [2]:
frutas[0]

'maça'

In [4]:
frutas[0:3]

['maça', 'banana', 'abacaxi']

In [5]:
frutas[1:]

['banana', 'abacaxi']

In [6]:
frutas[0:]

['maça', 'banana', 'abacaxi']

In [7]:
frutas[-1]

'abacaxi'

In [17]:
df_acoes = pd.read_csv('/content/bovespa_tidy.csv', sep=',')
df_acoes

     Ticker        Date      Close       High        Low       Open    Volume
0     VALE3  2024-10-09  51.927876  52.013061  51.323073  51.680843  22758400
1     VALE3  2024-10-10  52.174911  52.345279  51.748994  52.345279  17192100
2     VALE3  2024-10-11  52.924522  53.043779  51.944911  51.953431  20939400
3     VALE3  2024-10-14  52.754158  53.256741  52.243058  53.086373  44954000
4     VALE3  2024-10-15  52.106762  52.132319  51.595662  52.047134  25559300
...     ...         ...        ...        ...        ...        ...       ...
3987  MGLU3  2026-10-05   9.450000   9.790000   8.430000   8.430000  65568900
3988  MGLU3  2026-10-06   9.240000   9.920000   9.200000   9.510000  47644200
3989  MGLU3  2026-10-07   9.710000  10.080000   9.200000   9.230000  51155600
3990  MGLU3  2026-10-08  10.250000  10.830000   9.600000   9.750000  56420800
3991  MGLU3  2026-10-09  12.220000  12.450000  10.360000  10.550000  77512100

[3992 rows x 7 columns]

In [26]:
df_vale = df_acoes[(df_acoes['Ticker'] == 'VALE3') & (df_acoes['Close'] > 52)]
df_vale

    Ticker        Date      Close       High        Low       Open    Volume
1    VALE3  2024-10-10  52.174911  52.345279  51.748994  52.345279  17192100
2    VALE3  2024-10-11  52.924522  53.043779  51.944911  51.953431  20939400
3    VALE3  2024-10-14  52.754158  53.256741  52.243058  53.086373  44954000
4    VALE3  2024-10-15  52.106762  52.132319  51.595662  52.047134  25559300
5    VALE3  2024-10-16  53.103413  53.137487  52.456019  52.754160  29731800
..     ...         ...        ...        ...        ...        ...       ...
494  VALE3  2026-10-05  71.400002  74.269997  69.519997  73.379997  71273400
495  VALE3  2026-10-06  70.370003  71.970001  69.500000  71.970001  30284200
496  VALE3  2026-10-07  68.750000  69.900002  68.129997  69.900002  38890600
497  VALE3  2026-10-08  67.639999  69.360001  67.550003  68.190002  38819200
498  VALE3  2026-10-09  67.900002  68.309998  67.110001  68.160004  28275900

[287 rows x 7 columns]

In [28]:
df_acoes['Ticker'].unique()

array(['VALE3', 'PETR4', 'ITUB4', 'BBDC4', 'ABEV3', 'B3SA3', 'WEGE3',
       'MGLU3'], dtype=object)

In [29]:
df1 = df_vale.loc[:, 'Date']
df1

1      2024-10-10
2      2024-10-11
3      2024-10-14
4      2024-10-15
5      2024-10-16
          ...
494    2026-10-05
495    2026-10-06
496    2026-10-07
497    2026-10-08
498    2026-10-09
Name: Date, Length: 287, dtype: object

In [34]:
df2 = df_vale.loc[475:488, ['Ticker', 'Open', 'Close']]
df2

    Ticker       Open      Close
475  VALE3  79.599998  79.019997
476  VALE3  78.500000  79.099998
477  VALE3  77.779999  78.230003
478  VALE3  78.209999  78.199997
479  VALE3  76.500000  75.480003
480  VALE3  75.839996  74.599998
481  VALE3  75.059998  73.000000
482  VALE3  73.699997  74.510002
483  VALE3  74.139999  73.370003
484  VALE3  73.980003  72.550003
485  VALE3  72.400002  72.830002
486  VALE3  72.300003  71.480003
487  VALE3  71.519997  70.660004
488  VALE3  70.680000  70.769997

In [41]:
df3 = df_vale.iloc[0]

In [42]:
df3

Ticker         VALE3
Date      2024-10-10
Close      52.174911
High       52.345279
Low        51.748994
Open       52.345279
Volume      17192100
Name: 1, dtype: object

In [45]:
df4 = df_vale.iloc[0:4, :]
df4

  Ticker        Date      Close       High        Low       Open    Volume
1  VALE3  2024-10-10  52.174911  52.345279  51.748994  52.345279  17192100
2  VALE3  2024-10-11  52.924522  53.043779  51.944911  51.953431  20939400
3  VALE3  2024-10-14  52.754158  53.256741  52.243058  53.086373  44954000
4  VALE3  2024-10-15  52.106762  52.132319  51.595662  52.047134  25559300